language: node_js
node_js: stable
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - git config --global user.name "A1exLiu"
  - git config --global user.email "21982749+A1exInamin@users.noreply.github.com"
  - npm install -g hexo-cli
  - export HEXO_DEPLOYER_REPO=https://$REPO_TOKEN@github.com/A1exInamin/A1exInamin.github.io.git
install:
  - npm install -g hexo
  - npm install -g hexo-cli
  - npm install
script:
  - hexo clean
  - hexo generate
  - hexo deploy
