language: node_js
node_js:
  - 'lts/*'
  # - 'stable'
script: "true"
branches:
  only:
    - hexo
cache:
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Shanghai'
  - git config --global push.default matching
  - git config --global user.name "Travis CI"
  - git config --global user.email "bot@travis-ci.org"
  - sed -i'' "s~git@github.com:A1exMinatoooo/A1exInamin.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/A1exMinatoooo/A1exInamin.github.io.git~" _config.yml
install:
  - npm install -g hexo-cli
  - npm install
deploy:
  skip_cleanup: true
  provider: script
  script: sh deploy.sh
  on:
    branch: hexo
