language: node_js
node_js: stable
branches:
  only:
    - hexo
cache:
  directories:
    - node_modules
before_install:
  - git config --global push.default matching
  - git config --global user.name "A1exLiu via Travis CI"
  - git config --global user.email "21982749+A1exInamin@users.noreply.github.com"
  - sed -i'' "s~git@github.com:A1exInamin/A1exInamin.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/A1exInamin/A1exInamin.github.io.git~" _config.yml
install:
  - npm install -g hexo-cli
  - npm install
deploy:
  skip_cleanup: true
  provider: script
  script: sh deploy.sh
  on branch: master